const loveQuotes = [
  'Seu sorriso é como um raio de sol que ilumina até os meus dias mais sombrios.',
  'Cada momento ao seu lado é uma página inesquecível no livro da minha vida.',
  'Nos seus braços, encontrei o lar que sempre procurei.',
  'Você transforma a simplicidade do cotidiano em uma aventura extraordinária.',
  'Seu amor é a melodia que embala meu coração em um ritmo perfeito.',
  'Com você, cada dia é uma nova oportunidade de ser feliz.',
  'Seu olhar é um oceano no qual eu mergulho sem medo de me perder.',
  'Você é a razão pela qual acredito que a magia realmente existe.',
  'Seu toque é a brisa suave que acalma minha alma inquieta.',
  'A vida ao seu lado é um sonho do qual nunca quero acordar.',
  'Você é a estrela que ilumina meu céu, mesmo nas noites mais escuras.',
  'Seu amor é o combustível que me impulsiona a ser a melhor versão de mim mesmo.',
  'Com você, o tempo parece parar, e cada segundo é precioso.',
  'Você é a peça que faltava no quebra-cabeça do meu coração.',
  'Seu carinho é o remédio que cura todas as minhas feridas.',
  'Você é a poesia que dá sentido às palavras do meu coração.',
  'Seu amor é a âncora que me mantém firme em meio às tempestades.',
  'Com você, a vida é uma dança harmoniosa e cheia de alegria.',
  'Você é o sonho que se tornou realidade e superou todas as minhas expectativas.',
  'Seu abraço é o refúgio onde encontro paz e segurança.',
  'Você é a luz que guia meu caminho, mesmo quando tudo parece incerto.',
  'Seu amor é a aventura mais emocionante que já vivi.',
  'Com você, cada dia é uma nova chance de criar memórias inesquecíveis.',
  'Você é a razão pela qual meu coração bate mais forte a cada manhã.',
  'Seu sorriso é a chave que destranca todas as portas do meu coração.',
  'Você é a inspiração que transforma meus dias comuns em extraordinários.',
  'Seu amor é o tesouro mais precioso que guardo com todo o cuidado.',
  'Com você, a vida é um conto de fadas que se desenrola a cada dia.',
  'Você é a melodia que toca suavemente na trilha sonora da minha vida.',
  'Seu amor é a chama que mantém meu espírito aquecido e iluminado.',
]

export default loveQuotes
